image: python:3.8-buster

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: 1  
  BRANCH_NAME: "convert_test"              # Name of the branch to modify
  BOT_NAME: "GitLab Runner Bot"              # Bot's name that appears in the commit log
  BOT_EMAIL: "gitlab-runner-bot@example.net" # Bot's email, not important
  COMMIT_MESSAGE: "Commit from runner "      # Part of the commit message

before_script:
  - pip install -r requirements.txt

stages:          
  - test
  - convert

test_whitelists:
  stage: test
  script:
    - test/test_whitelists.py

convert_whitelists:
  stage: convert
  script:
    - misc/convert.py
    - git status
    - git checkout 'convert_test'
    - git status
    - git add misc/json
    - git status
    - git push -o ci.skip "https://whatever:${GIT_PUSH_TOKEN}@${CI_REPOSITORY_URL#*@}" $BRANCH_NAME
   