image: python:3.8-buster

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: 1  
  BRANCH_NAME: "convert_test"              # Name of the branch to modify
  BOT_NAME: "GitLab Runner Bot"              # Bot's name that appears in the commit log
  BOT_EMAIL: "gitlab-runner-bot@example.net" # Bot's email, not important
  COMMIT_MESSAGE: "Commit from runner "      # Part of the commit message

before_script:
  - pip install -r requirements.txt

stages:          
  - test
  - convert
  - merge

test_whitelists:
  stage: test
  script:
    - test/test_whitelists.py

convert_whitelists:
  stage: convert
  script:
    - misc/convert.py
    - git config --global user.name "${BOT_NAME}"
    - git config --global user.email "${BOT_EMAIL}"
    - git checkout -b $BRANCH_NAME
    - git add misc/json
    - git commit -m 'convert whitelists'
    - git push -o ci.skip "https://whatever:${GIT_PUSH_TOKEN}@${CI_REPOSITORY_URL#*@}" $BRANCH_NAME

merge_branch:
  stage: merge
  script:
    - git fetch
    - git status
    - git merge $BRANCH_NAME
    - git push -o ci.skip
    - git branch -D $BRANCH_NAME
   