image: python:3.8-buster

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - pip install -r requirements.txt

stages:          
  - test

test_whitelists:
  stage: test
  script:
    - test/test_whitelists.py
