name: label_and_merge_PR

on:
  pull_request_target:

jobs:
  Label-PR:
    runs-on: ubuntu-latest
    steps:
      - uses: Wizkas0/LabelGenAction@1.0.1
        with:
          repo-token: ${{ secrets.MY_TOKEN }}
          keyword-dict: | 
            { 
            "upstream branch main":"automerge"
            }
            
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.MY_TOKEN }}"