name: Sync Upstream

on:
  schedule:
    - cron: '30 22 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.MY_TOKEN }}
      
      - name: Upstream to PR
        uses: fopina/upstream-to-pr@8dd84d9d6ea941cc3d474c17233adb9cdd88555e
        with:
          token: ${{ secrets.MY_TOKEN }}
          upstream-repository: https://github.com/loosolab/whitelists.git
 